INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('AC','Acre');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('AL','Alagoas');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('AM','Amazonas');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('AP','Amapá¡');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('BA','Bahia');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('CE','Ceará¡');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('DF','Distrito Federal');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('ES','Espírito Santo');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('GO','Goiás');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('MA','Maranhão');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('MG','Minas Gerais');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('MS','Mato Grosso do Sul');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('MT','Mato Grosso');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('PA','Pará');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('PB','Paraíba');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('PE','Pernambuco');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('PI','Piauí');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('PR','Paraná');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('RJ','Rio de Janeiro');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('RN','Rio Grande do Norte');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('RO','Rondônia');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('RR','Roraima');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('RS','Rio Grande do Sul');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('SC','Santa Catarina');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('SE','Sergipe');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('SP','São Paulo');
INSERT INTO PROVINCE (ACRONYM,NAME) VALUES ('TO','Tocantins');

INSERT INTO ROLE VALUES ('CUS01','CUSTOMER','Clientes');
INSERT INTO ROLE VALUES ('EMP01','EMPLOYEE','Colaborador');
INSERT INTO ROLE VALUES ('JOB01','JOB','Cargo');
INSERT INTO ROLE VALUES ('CAT01','CATEGORY','Categoria');
INSERT INTO ROLE VALUES ('PRO01','PRODUCT','Produto');
INSERT INTO ROLE VALUES ('NCM01','NCM','NCM');
INSERT INTO ROLE VALUES ('SUP01','SUPPLIER','Fornecedor');
INSERT INTO ROLE VALUES ('NOP01','NATURE_OF_OPERATION','Natureza da Operação');
INSERT INTO ROLE VALUES ('SHI01','SHIPPER','Transportadora');
INSERT INTO ROLE VALUES ('PRE01','PREFERENCE','Preferências');
INSERT INTO ROLE VALUES ('USER1','USER','User');
INSERT INTO ROLE VALUES ('PRF01','PROFILE','Perfil');
INSERT INTO ROLE VALUES ('ADM01','MANAGER_PRICE','Administração de Preços');
INSERT INTO ROLE VALUES ('ALL','CLOSE','Fechar');
INSERT INTO ROLE VALUES ('CAR01','SHIPPER','Transportadora');
INSERT INTO ROLE VALUES ('IIP01','INVOICE_INPUT','Nota Fiscal Entrada');
INSERT INTO ROLE VALUES ('PSO01','PURCHASE_ORDER','Pedidos');
INSERT INTO ROLE VALUES ('PRS01','PRODUCT_SET','Conjuntos');
INSERT INTO ROLE VALUES ('SAL01','SALE_ORDER','Pedido de Venda');

insert into profile (ID,NAME,LABEL) values (1,'Administrador','Administrador do Sistema');

insert into PROFILE_ROLE (SELECT 1,key FROM role);

INSERT INTO USERS (ID,USERNAME,PASSWORD,EMPLOYEE,PROFILE,STATUS,BLOCKED) values (1,'ADMIN','brutal',null,1,'ACTIVE',0);

