INSERT INTO ROLE VALUES ('CUS01','CUSTOMER','Clientes');
INSERT INTO ROLE VALUES ('EMP01','EMPLOYEE','Colaborador');
INSERT INTO ROLE VALUES ('JOB01','JOB','Cargo');
INSERT INTO ROLE VALUES ('CAT01','CATEGORY','Categoria');
INSERT INTO ROLE VALUES ('PRO01','PRODUCT','Produto');
INSERT INTO ROLE VALUES ('NCM01','NCM','NCM');
INSERT INTO ROLE VALUES ('SUP01','SUPPLIER','Fornecedor');
INSERT INTO ROLE VALUES ('NOP01','NATURE_OF_OPERATION','Natureza da Operação');
INSERT INTO ROLE VALUES ('SHI01','SHIPPER','Transportadora');
INSERT INTO ROLE VALUES ('PRE01','PREFERENCE','Preferências');
INSERT INTO ROLE VALUES ('USER1','USER','User');
INSERT INTO ROLE VALUES ('PRF01','PROFILE','Perfil');
INSERT INTO ROLE VALUES ('ADM01','MANAGER_PRICE','Administração de Preços');
INSERT INTO ROLE VALUES ('ALL','CLOSE','Fechar');
INSERT INTO ROLE VALUES ('CAR01','SHIPPER','Transportadora');
INSERT INTO ROLE VALUES ('IIP01','INVOICE_INPUT','Nota Fiscal Entrada');
INSERT INTO ROLE VALUES ('PSO01','PURCHASE_ORDER','Pedidos');
INSERT INTO ROLE VALUES ('PRS01','PRODUCT_SET','Conjuntos');
INSERT INTO ROLE VALUES ('SAL01','SALE_ORDER','Pedido de Venda');

insert into profile (ID,NAME,LABEL) values (1,'Administrador','Administrador do Sistema');

insert into PROFILE_ROLE (SELECT 1,key FROM role);

INSERT INTO USERS (ID,USERNAME,PASSWORD,EMPLOYEE,PROFILE,STATUS,BLOCKED) values (1,'ADMIN','brutal',null,1,'ACTIVE',0);

